version: '3.8'

services:
  hls-server:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./output:/app/output
      - ./uploads:/app/uploads
    env_file:
      - .env
    restart: unless-stopped